### ISSUE TITLE
Allow deletion

### ISSUE THREAD

**Issue by aronerben** [jerben/memb#2]
Allow deletion of entries.
Suggestion: -d as a flag for deletion.
If more than one entries match the search term, a confirmation message appears mentioning the number of found matches.

Example 1 (one result):
```
memb -d "tar"
Deleted statement: WHOLE STATEMENT HERE
```

Example 2 (multiple results):
```
memb -d "tar"
2 statements match the given search-term, are you sure you want to delete all 2 entries? [y/n]
```
y -> `Deleted 2 statements.`
n -> Do nothing.

**Comment by joseferben** [comment]
Fixed, although only deletion per line number is possible at the moment.
