### ISSUE TITLE
[BUG] Deleting non existing line number no error

### ISSUE THREAD

**Issue by aronerben** [jerben/memb#6]
Steps to reproduce:
1. `memb -d X` where `X` is a line number that does not exist.

Expected result:
An error that tells the user the line does not exist, e.g.
`This entry does not exist.`

Actual result:
Prints:
`Removed line number X` where `X` is a line number that does not exit.

**Comment by joseferben** [comment]
Thanks for reporting! The fixed version is available in the AUR.
